zfs: C: Redesign role to support SELinux

diff --git a/zfs/templates/main/zfs_scrub-pools.j2 b/zfs/templates/main/zfs_scrub-pools.j2
--- a/zfs/templates/main/zfs_scrub-pools.j2
+++ b/zfs/templates/main/zfs_scrub-pools.j2
@@ -8,7 +8,7 @@
 # INFORMATION
 #-------------------------------------------------------------------------------
 #
-# Name   : zfs_check-pools.sh
+# Name   : zfs_scrub-pools
 # Type   : Shell script
 # Role   : zfs
 #
@@ -29,7 +29,6 @@ PATH='/sbin:/bin:/usr/sbin:/usr/bin'
 #-------------------------------------------------------------------------------
 
 which='/usr/bin/which' && [ -x ${which} ] || { echo "Error: Command 'which' not found."; exit 127; }
-awk=$(${which} awk) || { echo "Error: Command 'awk' not found."; exit 127; }
 basename=$(${which} basename) || { echo "Error: Command 'basename' not found."; exit 127; }
 date=$(${which} date) || { echo "Error: Command 'date' not found."; exit 127; }
 echo=$(${which} echo) || { echo "Error: Command 'echo' not found."; exit 127; }
@@ -54,18 +53,19 @@ zpool=$(${which} zpool) || { echo "Error: Command 'zpool' not found."; exit 127;
 host=$(${hostname} -s) || { echo "Error: Host name unknown."; exit 68; }
 script="$(${basename} $0)[$$]" || { echo "Error: Command invoked cannot execute."; exit 126; }
 time_start=$(${date} '+%s')
-user='{{file_owner_zfs_check_pools_sh}}'
-lockfile='{{file_dst_zfs_script_dir}}/zfs_check-pools.lock'
+user='{{file_owner_zfs_scrub_pools}}'
+lockfile='/var/tmp/zfs_scrub-pools.lock'
 retval=0
 severity='Debug'
 message='Please check log files for more information.'
 
 textfile_collector='{{zfs_monitor_prom_textfile_collector}}'
+zfs_scrub_pools_pools='{% for item in zfs_scrub_pools_pools %}{{item}}{% if not loop.last %} {% endif %}{% endfor %}'
 
 {% if (zfs_monitor_mail_state is match('true|yes|enable')) %}
 mail_from_address='{{zfs_monitor_mail_from_address}}'
 mail_to_address='{% for item in zfs_monitor_mail_to_address %}{{item}}{% if not loop.last %},{% endif %}{% endfor %}'
-mail_subject='zfs: Check Pool - Error ({{ansible_hostname}})'
+mail_subject='zfs: Scrub Pool - Error ({{ansible_hostname}})'
 {% endif %}
 
 #-------------------------------------------------------------------------------
@@ -89,7 +89,7 @@ Date & Time : $(${date} '+%Y-%m-%dT%H:%M:%S%z')
 SCRIPT
 --------------------------------------------------------------------------------
 
-Name        : zfs_check-pools.sh
+Name        : zfs_scrub-pools
 Type        : Shell script
 PID         : $$
 
@@ -115,28 +115,44 @@ update_prom() {
   time_exec="$3"
 
   if [ -w "${textfile_collector}" ]; then
-    ${echo} -e "# HELP zfs_check_pools_exit The script's exit code.\n"\
-"# TYPE zfs_check_pools_exit counter\n"\
-"zfs_check_pools_exit ${retval}" > "${textfile_collector}/zfs_check_pools_exit.prom"
+    ${echo} -e "# HELP zfs_scrub_pools_exit The script's exit code.\n"\
+"# TYPE zfs_scrub_pools_exit counter\n"\
+"zfs_scrub_pools_exit ${retval}" > "${textfile_collector}/zfs_scrub_pools_exit.prom"
 
     if [ -z "${time_start}" ] ; then
-      ${rm} -f "${textfile_collector}/zfs_check_pools_start.prom"
+      ${rm} -f "${textfile_collector}/zfs_scrub_pools_start.prom"
     else
-      ${echo} -e "# HELP zfs_check_pools_start The script's start time in epoch.\n"\
-"# TYPE zfs_check_pools_start counter\n"\
-"zfs_check_pools_start ${time_start}" > "${textfile_collector}/zfs_check_pools_start.prom"
+      ${echo} -e "# HELP zfs_scrub_pools_start The script's start time in epoch.\n"\
+"# TYPE zfs_scrub_pools_start counter\n"\
+"zfs_scrub_pools_start ${time_start}" > "${textfile_collector}/zfs_scrub_pools_start.prom"
     fi
 
     if [ -z "${time_exec}" ] ; then
-      ${rm} -f "${textfile_collector}/zfs_check_pools_duration.prom"
+      ${rm} -f "${textfile_collector}/zfs_scrub_pools_duration.prom"
     else
-      ${echo} -e "# HELP zfs_check_pools_duration The script's execution duration in seconds.\n"\
-"# TYPE zfs_check_pools_duration counter\n"\
-"zfs_check_pools_duration ${time_exec}" > "${textfile_collector}/zfs_check_pools_duration.prom"
+      ${echo} -e "# HELP zfs_scrub_pools_duration The script's execution duration in seconds.\n"\
+"# TYPE zfs_scrub_pools_duration counter\n"\
+"zfs_scrub_pools_duration ${time_exec}" > "${textfile_collector}/zfs_scrub_pools_duration.prom"
     fi
   fi
 }
 {% endif %}
+
+watch_and_wait_for_change() {
+  watch_key="$1"
+  watch_value="$2"
+  watch_option="$3"
+  time_step="$4"
+  time_maximum="$5"
+  while ${watch_key} | ${grep} ${watch_option} "${watch_value}" > /dev/null 2>&1 ; do
+    if [ "${time_initial}" -lt "${time_maximum}" ]; then
+      time_initial=$(${expr} "${time_initial}" + "${time_step}")
+      ${sleep} "${time_initial}"
+    else
+      ${sleep} "${time_initial}"
+    fi
+  done
+}
 
 check_script_user() {
   if [ "$(${whoami})" != "${user}" ]; then
@@ -196,7 +212,11 @@ log_and_exit() {
 
   retval=0
   severity='Info'
-  message='All ZFS pools are healthy.'
+  if [ -z "${zfs_scrub_pools_pools}" ]; then
+    message='No ZFS pools have been specified for scrubbing.'
+  else
+    message='Specified ZFS pools have been scrubbed and are healthy.'
+  fi
   ${logger} -t "${script}" "${severity}: ${message} Duration: ${time_hr}"
 
 {% if (zfs_monitor_prom_state is match('true|yes|enable')) %}
@@ -214,15 +234,36 @@ check_script_user
 
 create_lockfile
 
+# Scrub ZFS pools
+for pool in ${zfs_scrub_pools_pools} ; do
+  # Wait until previous scrub has finished
+  time_initial=0
+  watch_and_wait_for_change "${zpool} status" 'scrub in progress' '' '5' '300'
+
+  # Scrub next ZFS pool
+  ${zpool} scrub ${pool}
+  log_and_exit_on_error "$?" 'Error' "Unable to scrub ZFS pool: '${pool}'"
+done
+
 # Check ZFS pools
-for pool in $(${zpool} list | ${awk} '!/NAME/{print $1}') ; do
-  # Get ZFS pool status
+for pool in ${zfs_scrub_pools_pools} ; do
+  # Wait until previous scrub has finished
+  time_initial=0
+  watch_and_wait_for_change "${zpool} status" 'scrub in progress' '' '5' '300'
+
+  # Get next ZFS pool status
   zfs_pool_status="$(${zpool} status -xv ${pool})"
   log_and_exit_on_error "$?" 'Error' "Unable to get ZFS pool status: '${pool}'"
 
-  # Check ZFS pool status
+  # Check next ZFS pool status
   echo "${zfs_pool_status}" | ${grep} 'healthy' > /dev/null 2>&1
-  log_and_exit_on_error "$?" 'Critical' "ZFS pool is unhealthy: '${pool}'"
+  if [ "$?" -eq 0 ]; then
+    severity='Info'
+    message="ZFS pool has been scrubbed and is healthy: '${pool}'"
+    ${logger} -t "${script}" "${severity}: ${message}"
+  else
+    log_and_exit_on_error "$?" 'Critical' "ZFS pool is unhealthy: '${pool}'"
+  fi
 done
 
 remove_lockfile
